// import localFont from "next/font/local";
// import "./globals.css";
// import { AuthProvider } from "./provider";
// import { CartProvider } from "./context/CartContext";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Auto part bazar",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <AuthProvider>{children}</AuthProvider>
        
//       </body>
//     </html>
//   );
// }


// export default function RootLayout({ children }) {
//   return (
//     <CartProvider>
//       {children}
//     </CartProvider>
//   );
// }
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./provider";
import { CartProvider } from "./context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Auto Part Bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider> {/* ✅ Wrap CartProvider inside AuthProvider */}
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
